# Generated by Django 5.2.7 on 2025-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_remove_post_highlight_post_exam_file_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
