# Generated by Django 5.2.7 on 2025-11-26 13:32
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
