# Generated by Django 5.2.8 on 2025-12-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20251126_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
