# Generated by Django 5.2.8 on 2025-12-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_remove_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
